### ISSUE TITLE
Invalid DOM property fetchpriority

### ISSUE THREAD

**Issue by henrijoss** [porsche-design-system/porsche-design-system#3522]
Scope
---
The `p-model-signature` DSR component uses the wrong attribute case for `fetchpriority` causing following warning:

![Image](https://github.com/user-attachments/assets/07ec9ace-764f-4074-bdd7-ee731a1ca513)

Notes  
---
- Also check for other DSR components weather `fetchpriority` / `fetchPriority` is used correctly
- Maybe we should force any warning in our DSR test environment to throw an error instead
- Maybe we shouldn't use `@ts-ignore` in favour of `@ts-expect-error` when absolutely necessary
- [Community thread](https://porschedev.slack.com/archives/CT7AVHTTQ/p1728281697763589)

Acceptance criteria
---
- [x] No warning is shown when DSR component is used for the attribute / property `fetchpriority` / `fetchPriority`

Subtasks
---
- [ ] Task

**Comment by henrijoss** [comment]
Changing the casing to camelCase `fetchPriority` produced following issue in react/next.js:

```
stderr | tests/unit/specs/react-ssr-wrapper.spec.tsx > should render dsr component for PLinkTileModelSignature
Warning: React does not recognize the `fetchPriority` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fetchpriority` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at img
    at template
    at DSRModelSignature (/Users/henrijoss/projects/porsche-design-system/packages/components-react/projects/react-ssr-wrapper/src/lib/dsr-components/model-signature.tsx:18:1)
    at p-model-signature
    at /Users/henrijoss/projects/porsche-design-system/packages/components-react/projects/react-ssr-wrapper/src/lib/components/model-signature.wrapper.tsx:13:6
    at div
    at div
    at template
    at DSRLinkTileModelSignature (/Users/henrijoss/projects/porsche-design-system/packages/components-react/projects/react-ssr-wrapper/src/lib/dsr-components/link-tile-model-signature.tsx:20:1)
    at p-link-tile-model-signature
    at /Users/henrijoss/projects/porsche-design-system/packages/components-react/projects/react-ssr-wrapper/src/lib/components/link-tile-model-signature.wrapper.tsx:13:6
    at PorscheDesignSystemProvider (/Users/henrijoss/projects/porsche-design-system/packages/components-react/projects/react-ssr-wrapper/src/provider.tsx:14:3)
```

Seems to be fixed with React 19: https://github.com/facebook/react/pull/25927

**Comment by henrijoss** [comment]
Waiting for React 19 stable release
