### ISSUE TITLE
[BUG] - Carousel breaks if having a colon `:` in the aria label

### ISSUE THREAD

**Issue by leifmarcus** [porsche-design-system/porsche-design-system#3679]
### Contact Details

markus.wessollek.extern@porsche.digital

### JS Framework

Vue

### Porsche Design System version

3.23.0

### On which device(s) you can see the bug?

All devices, it's a javascript issue

### Reproduction Example

https://stackblitz.com/edit/psjogwuf?file=index.html

### Steps to reproduce the behavior

1. open the development console
2. Go to the [stackblitz link](https://stackblitz.com/edit/psjogwuf?file=index.html)
3. Find the error

### Expected behavior

The aria label should accept a colon in it.

My suggestion is, to make sure, to use real JSON inside the aria property. then the values can be passed using `JSON.stringify` and you can receive the values using `JSON.parse`. With html encoding this is not a problem.

```ts
// create aria label for PDS elements
const myAriaLabel = JSON.strigify({ 'aria-label': 'my: aria label' })
```

```jsx
{/* used for instance in jsx */}
<p-carousel aria={myAriaLabel} />
```

```html
<!-- html output encoded by the framework -->
<p-carousel aria="{&quot;aria-label&quot;:&quot;my: aria label&quot;}" />
```

### Relevant log output

```shell
SyntaxError: Expected ',' or '}' after property value in JSON at position 26 (line 1 column 27)
    at JSON.parse (<anonymous>)
    at en (porsche-design-syste…9a0b9a20.js:1:46292)
    at porsche-design-syste…9a0b9a20.js:1:57860
    at porsche-design-syste…9a0b9a20.js:1:58144
    at Array.map (<anonymous>)
    at Fi (porsche-design-syste…9a0b9a20.js:1:58130)
    at li.render (porsche-design-syste…22b46386.js:1:42644)
    at ge (porsche-design-syste…b9a0b9a20.js:1:9056)
    at fe (porsche-design-syste…b9a0b9a20.js:1:8862)
    at porsche-design-syste…b9a0b9a20.js:1:8539
```

**Comment by leifmarcus** [comment]
This is not only happening in the carousel, but in all places of the aria property like for instance on p-buttons
https://stackblitz.com/edit/phfnfsas?file=index.html
